#! /bin/sh

LUAJIT=./
BUILD_DIR=$LUAJIT/build

NDKABI=8
NDKVER=$NDK/toolchains/arm-linux-androideabi-4.6
NDKP=$NDKVER/prebuilt/darwin-x86/bin/arm-linux-androideabi-
NDKF="--sysroot=$NDK/platforms/android-$NDKABI/arch-arm -fno-exceptions -O3 -fsigned-char -fno-strict-aliasing -Wno-psabi -fvisibility=hidden -fno-short-enums -Wall -fomit-frame-pointer -fmessage-length=0 -Wno-unused -Wno-parentheses -pipe -mstructure-size-boundary=8 -mfpu=vfp -mfloat-abi=softfp -mthumb-interwork -march=armv5te -fPIC -I/Developer/Marmalade/6.2/s3e/edk/h -I/Developer/Marmalade/6.2/s3e/h -I/Developer/Marmalade/6.2/s3e/h/ext -I/Developer/Marmalade/6.2/modules/iwutil/h -I/Developer/Marmalade/6.2/modules/iwcore/h -I/Developer/android-ndk-r8b/sources/cxx-stl/gnu-libstdc++/4.4.3/include -I/Developer/android-ndk-r8b/sources/cxx-stl/gnu-libstdc++/4.4.3/libs/armeabi/include -I/Developer/android-ndk-r8b/platforms/android-$NDKABI/arch-arm/usr/include"
NDKLF="-Wl,-Bsymbolic -Wl,--no-undefined --sysroot=$NDK/platforms/android-$NDKABI/arch-arm -mthumb-interwork -L/Developer/Marmalade/6.2/s3e/edk/lib/android -L/Developer/android-ndk-r8b/sources/cxx-stl/gnu-libstdc++/4.4.3/libs/armeabi -L/Developer/android-ndk-r8b/platforms/android-$NDKABI/arch-arm/usr/lib -ledk -lplaceholderplaceholderplaceholderplaceholderplaceholder -lc -lm -llog -lgnustl_static -lgcc
"
make -C ./ HOST_CC="gcc -m32" CROSS=$NDKP TARGET_FLAGS="$NDKF" TARGET_FDFLAGS="$NDKLF" TARGET_SYS=Linux TARGET=arm TARGET_SONAME=libluajit.so clean
make -C ./ HOST_CC="gcc -m32" CROSS=$NDKP TARGET_FLAGS="$NDKF" TARGET_FDFLAGS="$NDKLF" TARGET_SYS=Linux TARGET=arm TARGET_SONAME=libluajit.so BUILDMODE=dynamic

mv $LUAJIT/src/libluajit.so $BUILD_DIR/libluajit.so

: '
adding PATH: /Developer/android-ndk-r8b/toolchains/arm-linux-androideabi-4.4.3/prebuilt/darwin-x86/bin
CFLAGS   = -O3 -include temp_defines_release.h -fsigned-char -fno-strict-aliasing -Wno-psabi -fvisibility=hidden -fno-short-enums -Wall -fomit-frame-pointer -fmessage-length=0 -Wno-unused -Wno-parentheses -pipe -mstructure-size-boundary=8 -mfpu=vfp -mfloat-abi=softfp -mthumb-interwork -march=armv5te
LINKFLAGS = -Wl,-Bsymbolic -Wl,--no-undefined --sysroot="/Developer/android-ndk-r8b/platforms/android-9/arch-arm" -mthumb-interwork -Wl,-Map="/Users/jmulro/Work/YiuClientBase/extensions/UMUpdateExt/lib/android/libUMUpdateExt.map"
arm-linux-androideabi-g++ -o release/UMUpdateExt_platform.os -c -fno-exceptions -O3 -include temp_defines_release.h -fsigned-char -fno-strict-aliasing -Wno-psabi -fvisibility=hidden -fno-short-enums -Wall -fomit-frame-pointer -fmessage-length=0 -Wno-unused -Wno-parentheses -pipe -mstructure-size-boundary=8 -mfpu=vfp -mfloat-abi=softfp -mthumb-interwork -march=armv5te -fPIC -I../source/h -I../h -I/Developer/Marmalade/6.2/s3e/edk/h -I/Developer/Marmalade/6.2/s3e/h -I/Developer/Marmalade/6.2/s3e/h/ext -I/Developer/Marmalade/6.2/modules/iwutil/h -I/Developer/Marmalade/6.2/modules/iwcore/h -I/Developer/android-ndk-r8b/sources/cxx-stl/gnu-libstdc++/4.4.3/include -I/Developer/android-ndk-r8b/sources/cxx-stl/gnu-libstdc++/4.4.3/libs/armeabi/include -I/Developer/android-ndk-r8b/platforms/android-9/arch-arm/usr/include /Users/jmulro/Work/YiuClientBase/extensions/UMUpdateExt/source/android/UMUpdateExt_platform.cpp
arm-linux-androideabi-g++ -o release/UMUpdateExt.os -c -fno-exceptions -O3 -include temp_defines_release.h -fsigned-char -fno-strict-aliasing -Wno-psabi -fvisibility=hidden -fno-short-enums -Wall -fomit-frame-pointer -fmessage-length=0 -Wno-unused -Wno-parentheses -pipe -mstructure-size-boundary=8 -mfpu=vfp -mfloat-abi=softfp -mthumb-interwork -march=armv5te -fPIC -I../source/h -I../h -I/Developer/Marmalade/6.2/s3e/edk/h -I/Developer/Marmalade/6.2/s3e/h -I/Developer/Marmalade/6.2/s3e/h/ext -I/Developer/Marmalade/6.2/modules/iwutil/h -I/Developer/Marmalade/6.2/modules/iwcore/h -I/Developer/android-ndk-r8b/sources/cxx-stl/gnu-libstdc++/4.4.3/include -I/Developer/android-ndk-r8b/sources/cxx-stl/gnu-libstdc++/4.4.3/libs/armeabi/include -I/Developer/android-ndk-r8b/platforms/android-9/arch-arm/usr/include /Users/jmulro/Work/YiuClientBase/extensions/UMUpdateExt/source/generic/UMUpdateExt.cpp
arm-linux-androideabi-g++ -o release/UMUpdateExt_register.os -c -fno-exceptions -O3 -include temp_defines_release.h -fsigned-char -fno-strict-aliasing -Wno-psabi -fvisibility=hidden -fno-short-enums -Wall -fomit-frame-pointer -fmessage-length=0 -Wno-unused -Wno-parentheses -pipe -mstructure-size-boundary=8 -mfpu=vfp -mfloat-abi=softfp -mthumb-interwork -march=armv5te -fPIC -I../source/h -I../h -I/Developer/Marmalade/6.2/s3e/edk/h -I/Developer/Marmalade/6.2/s3e/h -I/Developer/Marmalade/6.2/s3e/h/ext -I/Developer/Marmalade/6.2/modules/iwutil/h -I/Developer/Marmalade/6.2/modules/iwcore/h -I/Developer/android-ndk-r8b/sources/cxx-stl/gnu-libstdc++/4.4.3/include -I/Developer/android-ndk-r8b/sources/cxx-stl/gnu-libstdc++/4.4.3/libs/armeabi/include -I/Developer/android-ndk-r8b/platforms/android-9/arch-arm/usr/include /Users/jmulro/Work/YiuClientBase/extensions/UMUpdateExt/source/generic/UMUpdateExt_register.cpp
arm-linux-androideabi-g++ -o /Users/jmulro/Work/YiuClientBase/extensions/UMUpdateExt/lib/android/libUMUpdateExt.so -Wl,-Bsymbolic -Wl,--no-undefined --sysroot="/Developer/android-ndk-r8b/platforms/android-9/arch-arm" -mthumb-interwork -Wl,-Map="/Users/jmulro/Work/YiuClientBase/extensions/UMUpdateExt/lib/android/libUMUpdateExt.map" -shared release/UMUpdateExt_platform.os release/UMUpdateExt.os release/UMUpdateExt_register.os -L/Developer/Marmalade/6.2/s3e/edk/lib/android -L/Developer/android-ndk-r8b/sources/cxx-stl/gnu-libstdc++/4.4.3/libs/armeabi -L/Developer/android-ndk-r8b/platforms/android-9/arch-arm/usr/lib -ledk -lplaceholderplaceholderplaceholderplaceholderplaceholder -lc -lm -llog -lgnustl_static -lgcc
/Developer/android-ndk-r8b/toolchains/arm-linux-androideabi-4.4.3/prebuilt/darwin-x86/bin/../lib/gcc/arm-linux-androideabi/4.4.3/../../../../arm-linux-androideabi/bin/ld: Warning: /Developer/android-ndk-r8b/platforms/android-9/arch-arm/usr/lib/crtend_so.o: Unknown EABI object attribute 44
arm-linux-androideabi-strip "/Users/jmulro/Work/YiuClientBase/extensions/UMUpdateExt/lib/android/libUMUpdateExt.so"
Executing: '/usr/local/bin/scons -Q verbose=1 debug=1 compiler=arm-linux-androideabi-gcc'
CCFLAGS   = -g -O0 -include temp_defines_debug.h -fsigned-char -fno-strict-aliasing -Wno-psabi -fvisibility=hidden -fno-short-enums -Wall -fomit-frame-pointer -fmessage-length=0 -Wno-unused -Wno-parentheses -pipe -mstructure-size-boundary=8 -mfpu=vfp -mfloat-abi=softfp -mthumb-interwork -march=armv5te
CXXFLAGS  = -fno-exceptions
LINKFLAGS = -Wl,-Bsymbolic -Wl,--no-undefined --sysroot="/Developer/android-ndk-r8b/platforms/android-9/arch-arm" -mthumb-interwork -Wl,-Map="/Users/jmulro/Work/YiuClientBase/extensions/UMUpdateExt/lib/android/libUMUpdateExt_d.map"
SHLINKFLAGS = $LINKFLAGS -shared
CC        = arm-linux-androideabi-gcc
CXX       = arm-linux-androideabi-g++
arm-linux-androideabi-g++ -o debug/UMUpdateExt_platform.os -c -fno-exceptions -g -O0 -include temp_defines_debug.h -fsigned-char -fno-strict-aliasing -Wno-psabi -fvisibility=hidden -fno-short-enums -Wall -fomit-frame-pointer -fmessage-length=0 -Wno-unused -Wno-parentheses -pipe -mstructure-size-boundary=8 -mfpu=vfp -mfloat-abi=softfp -mthumb-interwork -march=armv5te -fPIC -I../source/h -I../h -I/Developer/Marmalade/6.2/s3e/edk/h -I/Developer/Marmalade/6.2/s3e/h -I/Developer/Marmalade/6.2/s3e/h/ext -I/Developer/Marmalade/6.2/modules/iwutil/h -I/Developer/Marmalade/6.2/modules/iwcore/h -I/Developer/android-ndk-r8b/sources/cxx-stl/gnu-libstdc++/4.4.3/include -I/Developer/android-ndk-r8b/sources/cxx-stl/gnu-libstdc++/4.4.3/libs/armeabi/include -I/Developer/android-ndk-r8b/platforms/android-9/arch-arm/usr/include /Users/jmulro/Work/YiuClientBase/extensions/UMUpdateExt/source/android/UMUpdateExt_platform.cpp
arm-linux-androideabi-g++ -o debug/UMUpdateExt.os -c -fno-exceptions -g -O0 -include temp_defines_debug.h -fsigned-char -fno-strict-aliasing -Wno-psabi -fvisibility=hidden -fno-short-enums -Wall -fomit-frame-pointer -fmessage-length=0 -Wno-unused -Wno-parentheses -pipe -mstructure-size-boundary=8 -mfpu=vfp -mfloat-abi=softfp -mthumb-interwork -march=armv5te -fPIC -I../source/h -I../h -I/Developer/Marmalade/6.2/s3e/edk/h -I/Developer/Marmalade/6.2/s3e/h -I/Developer/Marmalade/6.2/s3e/h/ext -I/Developer/Marmalade/6.2/modules/iwutil/h -I/Developer/Marmalade/6.2/modules/iwcore/h -I/Developer/android-ndk-r8b/sources/cxx-stl/gnu-libstdc++/4.4.3/include -I/Developer/android-ndk-r8b/sources/cxx-stl/gnu-libstdc++/4.4.3/libs/armeabi/include -I/Developer/android-ndk-r8b/platforms/android-9/arch-arm/usr/include /Users/jmulro/Work/YiuClientBase/extensions/UMUpdateExt/source/generic/UMUpdateExt.cpp
arm-linux-androideabi-g++ -o debug/UMUpdateExt_register.os -c -fno-exceptions -g -O0 -include temp_defines_debug.h -fsigned-char -fno-strict-aliasing -Wno-psabi -fvisibility=hidden -fno-short-enums -Wall -fomit-frame-pointer -fmessage-length=0 -Wno-unused -Wno-parentheses -pipe -mstructure-size-boundary=8 -mfpu=vfp -mfloat-abi=softfp -mthumb-interwork -march=armv5te -fPIC -I../source/h -I../h -I/Developer/Marmalade/6.2/s3e/edk/h -I/Developer/Marmalade/6.2/s3e/h -I/Developer/Marmalade/6.2/s3e/h/ext -I/Developer/Marmalade/6.2/modules/iwutil/h -I/Developer/Marmalade/6.2/modules/iwcore/h -I/Developer/android-ndk-r8b/sources/cxx-stl/gnu-libstdc++/4.4.3/include -I/Developer/android-ndk-r8b/sources/cxx-stl/gnu-libstdc++/4.4.3/libs/armeabi/include -I/Developer/android-ndk-r8b/platforms/android-9/arch-arm/usr/include /Users/jmulro/Work/YiuClientBase/extensions/UMUpdateExt/source/generic/UMUpdateExt_register.cpp
arm-linux-androideabi-g++ -o /Users/jmulro/Work/YiuClientBase/extensions/UMUpdateExt/lib/android/libUMUpdateExt_d.so -Wl,-Bsymbolic -Wl,--no-undefined --sysroot="/Developer/android-ndk-r8b/platforms/android-9/arch-arm" -mthumb-interwork -Wl,-Map="/Users/jmulro/Work/YiuClientBase/extensions/UMUpdateExt/lib/android/libUMUpdateExt_d.map" -shared debug/UMUpdateExt_platform.os debug/UMUpdateExt.os debug/UMUpdateExt_register.os -L/Developer/Marmalade/6.2/s3e/edk/lib/android -L/Developer/android-ndk-r8b/sources/cxx-stl/gnu-libstdc++/4.4.3/libs/armeabi -L/Developer/android-ndk-r8b/platforms/android-9/arch-arm/usr/lib -ledk -lplaceholderplaceholderplaceholderplaceholderplaceholder -lc -lm -llog -lgnustl_static -lgcc
/Developer/android-ndk-r8b/toolchains/arm-linux-androideabi-4.4.3/prebuilt/darwin-x86/bin/../lib/gcc/arm-linux-androideabi/4.4.3/../../../../arm-linux-androideabi/bin/ld: Warning: /Developer/android-ndk-r8b/platforms/android-9/arch-arm/usr/lib/crtend_so.o: Unknown EABI object attribute 44
###
'
